site_name: Lá cây xanh
site_description: tôi ăn cắp ý tưởng từ r/Frugal và kha khá chỗ khác
site_author: duykhanh471

nav:
  - 'Trang chủ': 'index.md'
  - 'Frugal': 'frugal.md'
  - 'Lối sống tối giản': 'loi-song-toi-gian.md'
  - 'Ăn uống': 'an-uong.md'
  - 'Lối sống và nhà cửa':
    - 'Chống chủ nghĩa tiêu dùng': 'anti-consumption.md'
    - 'Không chất thải': 'zero-waste.md'
    - 'Dọn dẹp': 'don-dep.md'
  - 'Tài chính & Mua sắm':
    - 'Quản lý tài chính': 'quan-ly-tai-chinh.md'
    - 'Mua đồ cũ': 'mua-do-cu.md'
  - 'Môi trường': 'moi-truong.md'
  - 'Gợi ý sách': 'goi-y-sach.md'


theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - search.highlighting
    - search.share
    - search.suggest
  name: material
  icon: leafy_green

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - meta
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
plugins:
  - search
  - open-in-new-tab

extra:
  generator: false
